config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'index' => 'home#index'

  namespace :admin do
    get 'login' => 'login#show'
    post 'login' => 'login#submit'

    get 'listings' => 'listings#index'
    post 'listings' => 'listings#create'
    patch 'listings' => 'listings#patch'

    get 'listings/new' => 'listings#new'
    get 'listings/:id/edit' => 'listings#edit'
    put 'listings/:id' => 'listings#update'

    resources :blacklists, only: [:index, :create, :update, :destroy]
    post 'sync' => 'sync#sync'
  end

end

app/models/blacklist.rb
# == Schema Information
#
# Table name: blacklists
#
#  id         :integer          not null, primary key
#  substring  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blacklist < ActiveRecord::Base
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  start_date     :date             not null
#  end_date       :date
#  address        :string           not null
#  title          :string           not null
#  link           :string           not null
#  blurb          :text             not null
#  hours          :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  venue          :string           default(""), not null
#  restricted_to  :string
#  source_lead_id :integer
#
# Indexes
#
#  index_events_on_start_date  (start_date)
#

class Event < ActiveRecord::Base
  scope :current, -> { where('start_date >= ?', Date.today) }
  validates_presence_of :title, :start_date, :address, :link, :blurb
  belongs_to :source_lead, class_name: 'Lead'

  def update_url
    "/admin/listings/#{id}"
  end
  def edit_url
    "/admin/listings/#{id}/edit"
  end
end

app/models/lead.rb
# == Schema Information
#
# Table name: leads
#
#  id           :integer          not null, primary key
#  source       :string
#  date         :date
#  title        :string
#  location     :string
#  url          :string
#  reviewed     :boolean          default(FALSE), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  key          :string
#  other_fields :json             default({}), not null
#
# Indexes
#
#  index_leads_on_date  (date)
#  index_leads_on_key   (key) UNIQUE
#

class Lead < ActiveRecord::Base
  scope :pending, -> { where('not reviewed and date >= ?', Date.today) }

  validates :key, uniqueness: true
  validates_presence_of :title, :date, :url
end

app/controllers/admin/blacklists_controller.rb
class Admin::BlacklistsController < ApplicationController
  before_action :set_blacklist, only: [:update, :destroy]
  before_action :require_admin

  # GET /admin/blacklists
  def index
    @blacklists = Blacklist.all.order(updated_at: :desc)
  end

  # POST /admin/blacklists
  def create
    @blacklist = Blacklist.new(blacklist_params)

    respond_to do |format|
      if @blacklist.save
        format.html { redirect_to admin_blacklists_url, notice: 'Blacklist entry successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin/blacklists/1
  # TODO this is currently unused
  def update
    respond_to do |format|
      if @blacklist.update(blacklist_params)
        format.html { redirect_to admin_blacklists_url, notice: 'Blacklist entry successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin/blacklists/1
  def destroy
    @blacklist.destroy
    respond_to do |format|
      format.html { redirect_to admin_blacklists_url, notice: 'Blacklist was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blacklist
      @blacklist = Blacklist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blacklist_params
      # TODO check!
      params.permit(:id, :substring)
    end
end

app/controllers/admin/listings_controller.rb
class Admin::ListingsController < ApplicationController
  helper_method :listings
  before_action :require_admin

  def index
    @event = Event.new
    @form_params = {url: '/admin/listings'}
  end

  def new
    @event = Event.new
    @form_params = {url: '/admin/listings'}
    if params[:lead_id]
      @lead = Lead.find_by_id(params[:lead_id])
      @event.update_attributes(
        title: @lead.title,
        start_date: @lead.date,
        link: @lead.url,
        address: @lead.location,
        source_lead_id: @lead.id
      )

      @event.update_attributes(@lead.other_fields)
    end
  end

  def create
    event = Event.create!(event_params)

    # If this was derived from a particular lead, mark that lead true when we
    # create the event
    lead = event.source_lead
    if event.source_lead
       lead.reviewed = true
       lead.save!
    end

    redirect_to admin_listings_url, notice: 'Post successfully created.'
  end

  def patch
    lead_ids = params.require(:reviewed_leads)
    lead_ids.each do |id|
      lead = Lead.find_by_id!(id.to_i)
      lead.reviewed = true
      lead.save!
    end

    notice = lead_ids.count > 0 ? "Hid #{lead_ids.count} lead(s)." : nil
    Rails.logger.info "NOTICE: #{notice}"
  
    redirect_to admin_listings_url, notice: notice
  end

  def edit
    @event = Event.find(params[:id])
    @form_params = {
      url: @event.update_url,
      method: :put
    }
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes!(event_params)
    redirect_to admin_listings_url, notice: 'Post successfully updated.'
  end

  def listings
    @listings ||= (Lead.pending.map do |lead|
      {
        lead_id: lead.id,
        source: lead.source,
        date: lead.date,
        title: lead.title,
        location: lead.location,
        url: lead.url
      }
    end + Event.current.map do |event|
      {
        event_id: event.id,
        edit_url: event.edit_url,
        date: event.start_date,
        title: event.title,
        location: event.address,
        url: event.link
      }
    end).sort_by { |x| [ x[:date], x[:title].downcase ] }
  end

private
  def event_params
    args = params.require(:event).permit(
      :title,
      :venue,
      :address,
      :link,
      :blurb,
      :start_date,
      :end_date,
      :hours,
      :restricted_to,
      :source_lead_id
    )

    args[:start_date] = Date.parse(args[:start_date])
    if args[:end_date].present?
      args[:end_date] = Date.parse(args[:end_date])
    else
      args.delete(:end_date)
    end
    if args[:hours].present?
      args[:hours] = args[:hours].to_i
    else
      args.delete(:hours)
    end

    args
  end
end

app/controllers/admin/login_controller.rb
class Admin::LoginController < ApplicationController
  def show
  end

  def submit
    password = params.require(:password)

    Rails.logger.info "App password: #{Rails.application.secrets.admin_password}"
    if password == Rails.application.secrets.admin_password
      session[:admin] = true
      redirect_to controller: :listings, action: :index
    else
      flash[:alert] = 'Incorrect password.'
      redirect_to action: :show
    end
  end
end

app/controllers/admin/sync_controller.rb
class Admin::SyncController < ApplicationController
  before_action :require_admin

  # POST /admin/sync
  def sync
    PollAndBlacklistJob.perform_later
    redirect_to admin_listings_url, notice: 'Sync started.'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_admin
    redirect_to controller: :login, action: :show if !session[:admin]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.current.order(:start_date)

    respond_to do |format|
      format.html
      format.atom
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/blacklists/index.html.erb
<main class="measure py2">
  <a href="/admin/listings">Back to listings</a>
  <h2>Blacklisted Phrases</h2>
  <form method="POST" class="grd">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="grd-row">
      <div class="grd-row-col-3-6">
        <input type="text" placeholder="substring" name="substring" required="required">
      </div>
      <div class="grd-row-col-2-6">
        <input class="btn--blue" type="submit" value="Add">
      </div>
    </div>
  </form>
  <table>
    <thead>
      <th></th>
      <th>Substring</th>
    </thead>
    <tbody>
      <% @blacklists.each do |bl| %>
        <tr>
          <td><%= link_to '✕', admin_blacklist_url(bl.id), method: :delete, class: 'fnt--red' %></td>
          <td class="h4"><code><%= bl.substring %></code></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

app/views/admin/listings/_form.html.erb
<%= form_for(@event, @form_params) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %> 

  <%= f.label :venue do %> Venue name <small>(optional)</small><% end %>
  <%= f.text_field :venue %>

  <%= f.label :address %>
  <%= f.text_field :address, required: true %>

  <%= f.label :link, 'Link URL' %>
  <%= f.url_field :link, required: true %>

  <%= f.label :blurb %>
  <%= f.text_area :blurb, required: true %>

  <%= f.label :start_date do %>Start date <small>(YYYY-MM-DD)</small><% end %>
  <%= f.date_field :start_date, required: true %>

  <%= f.label :end_date do %>End date <small>(YYYY-MM-DD, optional)</small><% end %>
  <%= f.date_field :end_date %>

  <%= f.label :hours do %>Hours <small>(optional)</small><% end %>
  <%= f.number_field :hours, step: 1 %>

  <%= f.label :restricted_to do %>Restricted to <small>(optional)</small><% end %>
  <%= f.text_field :restricted_to %>

  <%= f.hidden_field :source_lead_id %>

  <input class="btn--blue" type="submit" value="Submit">
<% end %>

app/views/admin/listings/edit.html.erb
<main class="measure py2">
  <a href="/admin/listings">Back to listings</a>
  <h2>Edit Event</h2>
  <%= render 'admin/listings/form' %>
</main>

app/views/admin/listings/index.html.erb
<main class="measure py2 grd">
  <h2>Review Leads</h2>

  <div class="grd-row">
    <div class="grd-row-col-3-6">
      <%= link_to 'Sync now', admin_sync_url, method: :post, class: 'fnt--green' %>
    </div>
    <div class="grd-row-col-3-6 txt--right">
      <a class="fnt--orange" href="/admin/blacklists">Manage blacklists</a>
    </div>
  </div>

  <form method="POST" class="grd-row">
    <input name="_method" type="hidden" value="patch">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <table>
      <thead>
        <th>Source</th>
        <th>✓</th>
        <th>Date</th>
        <th>Title</th>
        <th>Location</th>
        <th>✍</th>
      </thead>
      <tbody>
        <% listings.each do |listing| %>
          <tr class="<%= 'fnt--mid-gray' if !listing[:lead_id] %>">
            <td>
              <% if listing[:lead_id] %>
                <%= listing[:source] %>
              <% else %>
                <a class="fnt--green" href="<%= listing[:edit_url] %>">posted</a>
              <% end %>
            </td>
            <td>
              <% if listing[:lead_id] %>
                <input type="checkbox" name="reviewed_leads[]" value="<%= listing[:lead_id] %>">
              <% end %>
            </td>
            <td><%= listing[:date] %></td>
            <td><a href="<%= listing[:url] %>"><%= listing[:title] %></a></td>
            <td>
              <a href="<%=
                'https://maps.google.com?' + {
                  saddr: 'San Francisco, CA',
                  daddr: listing[:location]
                }.to_query %>">
                <%= listing[:location] %>
              </a>
            </td>
            <td>
              <%=
              if listing[:lead_id]
                link_to '➡', admin_listings_new_path(lead_id: listing[:lead_id]), class: 'fnt--green'
              end
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <input class="btn--red" type="submit" value="Hide checked items">
  </form>

  <h2>Create Event Listing</h2>
  <%= render 'admin/listings/form' %>
</main>

app/views/admin/listings/new.html.erb
<main class="measure py2">
  <a href="/admin/listings">Back to listings</a>
  <h2>Create Event</h2>
  <%= render 'admin/listings/form' %>
</main>

app/views/admin/login/show.html.erb
<main class="measure my2 p2">
  <h1 class="txt--center">Admin Login</h1>
  <form method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="grd">
      <div class="grd-row">
        <div class="grd-row-col-1-6 py2"></div>
        <div class="grd-row-col-3-6">
          <input type="password" id="password" name="password">
        </div>
        <div class="grd-row-col-1-6">
          <input class="btn--blue" type="submit" value="Log in">
        </div>
      </div>
      <div class="grd-row">
        <div class="grd-row-col-3-6"></div>
      </div>
    </div>
  </form>
</main>

app/views/home/index.html.erb
<%= content_for :head, auto_discovery_link_tag(:atom, index_url(format: "atom")) %>
<main class="measure py2">
  <h1 class="txt--center">San Francisco Hackathons</h1>
  <% @events.each do |event| %>
    <div id="e<%= event.id %>" class="brdr--off-white p1 my1 media">
      <div class="media-figure py1 brdr--light-gray txt--center calbox">
        <% if event.end_date && (event.end_date.month != event.start_date.month) %>
          <span>
            <div class="h5 p0 m0"><%= event.start_date.strftime('%b') %></div>
            <div class="h3 m00"><%= event.start_date.day %></div>
          </span>
          <span class="h3">-</span>
          <span>
            <div class="h5 p0 m0"><%= event.end_date.strftime('%b') %></div>
            <div class="h3 m00"><%= event.end_date.day %></div>
          </span>
        <% else %>
          <div style="width: 100%">
            <span class="h5 p0 m0 txt--left"><%= event.start_date.strftime('%b') %></span>
            <% if event.end_date && event.end_date.month != event.start_date.month %>
              <span class="h5 p0 m0 ">- <%= event.end_date.strftime('%b') %></span>
            <% end %>
          </div>
          <div class="h3 m00">
            <%= event.start_date.day %>
            <% if event.end_date %>
              - <%= event.end_date.day %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="media-body grd">
        <div class="grd-row">
          <div class="grd-row-col-4-6">
            <a class="h3 m00 p0 fnt--green" href="<%= event.link %>"><%= event.title %></a>
          </div>
          <% if event.hours %>
            <div class="grd-row-col-2-6">
                <span class="h3 muted">- <%= event.hours %> hours</span>
            </div>
          <% end %>
        </div>
        <div class="grd-row blurb"><%= event.blurb %></div>
        <% if event.restricted_to.present? %>
          <div class="grd-row fnt--orange">
            Only open to <%= event.restricted_to %>
          </div>
        <% end %>
        <div class="grd-row muted">
          <div>
            Hosted at <%= "<b>#{h(event.venue)}</b> - ".html_safe if event.venue.present? %>
            <a href="https://maps.google.com?q=<%=u event.address %>"><%= event.address %></a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</main>
<footer class="measure p2 grd">
  <div class="grd-row">
    <div class="grd-row-col-3-6"></div>
    <div class="grd-row-col-1-6">
      <%= link_to 'Atom feed', controller: 'home', action: :index, format: :atom %>
    </div>
    <div class="grd-row-col-1-6">
      <a href="https://github.com/tdeck/sfhacks">GitHub</a>
    </div>
    <div class="grd-row-col-1-6">
      <%= link_to 'Admin', controller: 'admin/listings', action: :index %>
    </div>
  </div>
</footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72560041-2', 'auto');
  ga('send', 'pageview');
</script>

app/views/home/show.html.erb
<main class="measure py2">
  <h1 class="txt--center">San Francisco Hackathons</h1>
  <% @events.each do |event| %>
    <div class="brdr--off-white p1 my1 media">
      <div class="media-figure py1 brdr--light-gray txt--center calbox">
        <div style="width: 100%">
          <span class="h5 p0 m0 txt--left"><%= event.start_date.strftime('%b') %></span>
          <% if event.end_date && event.end_date.month != event.start_date.month %>
            <span class="h5 p0 m0 ">- <%= event.end_date.strftime('%b') %></span>
          <% end %>
        </div>
        <div class="h3 m00">
          <%= event.start_date.day %>
          <% if event.end_date %>
            - <%= event.end_date.day %>
          <% end %>
        </div>
      </div>
      <div class="media-body grd">
        <div class="grd-row">
          <div class="grd-row-col-4-6">
            <a class="h3 m00 p0 fnt--green" href="<%= event.link %>"><%= event.title %></a>
          </div>
          <% if event.hours %>
            <div class="grd-row-col-2-6">
                <span class="h3 muted">- <%= event.hours %> hours</span>
            </div>
          <% end %>
        </div>
        <div class="grd-row blurb"><%= event.blurb %></div>
        <% if event.restricted_to.present? %>
          <div class="grd-row fnt--orange">
            Only open to <%= event.restricted_to %>
          </div>
        <% end %>
        <div class="grd-row muted">
          <div>
            Hosted at <%= "<b>#{h(event.venue)}</b> - ".html_safe if event.venue.present? %>
            <a href="https://maps.google.com?q=<%=u event.address %>"><%= event.address %></a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</main>
<footer class="measure p2 grd">
  <div class="grd-row">
    <div class="grd-row-col-4-6"></div>
    <div class="grd-row-col-1-6">
      <a href="https://github.com/tdeck/sfhacks">GitHub</a>
    </div>
    <div class="grd-row-col-1-6">
      <%= link_to 'Admin', controller: 'admin/listings', action: :index %>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SF Hackathons</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<% if flash[:alert] %>
  <div class="m00 px2 bg--red fnt--white h4"><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <div class="m00 px2 bg--green fnt--white h4"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>